# Auto-generated by viewer.py
SHEET = 'Assests/Sword Master Sprite Sheet 90x37.png'
FRAME_SIZE = (90, 37)
MARGIN = 0
SPACING = 0
FRAMES = [
    (0, 518, 90, 37),
    (90, 518, 90, 37),
    (180, 518, 90, 37),
    (270, 518, 90, 37),
]
