# Auto-generated by viewer.py
SHEET = 'Assests/Sword Master Sprite Sheet 90x37.png'
FRAME_SIZE = (90, 37)
MARGIN = 0
SPACING = 0
FRAMES = [
    (0, 74, 90, 37),
    (90, 74, 90, 37),
    (180, 74, 90, 37),
    (270, 74, 90, 37),
    (360, 74, 90, 37),
    (450, 74, 90, 37),
    (540, 74, 90, 37),
    (630, 74, 90, 37),
]
