# Auto-generated by sprite animation tool
ANIMATION = 'staticIdle'
SHEET = '../../../Assests/SwordMaster/Sword Master Sprite Sheet.png'
FRAME_SIZE = (90, 37)
MARGIN = 1
SPACING = 2
FRAMES = [
    {'x': 1, 'y': 1, 'w': 90, 'h': 37, 'row': 0, 'col': 0, 'trimmed': {'x': 17, 'y': 11, 'w': 23, 'h': 24}, 'offset': {'x': 16, 'y': 10}, 'pivot': {'x': 11, 'y': 23}},
]
TRIMMED = [
    (17, 11, 23, 24, 16, 10),
]
PIVOTS = [
    (11, 23),
]
