# Auto-generated by viewer.py
ANIMATION = 'fall'
SHEET = 'Assests/Sword Master Sprite Sheet 90x37.png'
FRAME_SIZE = (90, 37)
MARGIN = 0
SPACING = 0
FRAMES = [
    (0, 555, 90, 37),
    (90, 555, 90, 37),
    (180, 555, 90, 37),
]
TRIMMED = [
    (17, 564, 19, 21, 17, 9),
    (107, 564, 19, 21, 17, 9),
    (197, 564, 19, 21, 17, 9),
]
PIVOTS = [
    (9, 20),
    (9, 20),
    (9, 20),
]
