# Auto-generated by viewer.py
ANIMATION = 'jump'
SHEET = 'Assests/Sword Master Sprite Sheet 90x37.png'
FRAME_SIZE = (90, 37)
MARGIN = 0
SPACING = 0
FRAMES = [
    (0, 481, 90, 37),
    (90, 481, 90, 37),
    (180, 481, 90, 37),
]
TRIMMED = [
    (22, 490, 12, 23, 22, 9),
    (112, 490, 12, 23, 22, 9),
    (202, 490, 12, 23, 22, 9),
]
PIVOTS = [
    (6, 22),
    (6, 22),
    (6, 22),
]
