# Auto-generated by viewer.py
ANIMATION = 'trans'
SHEET = 'Assests/Sword Master Sprite Sheet 90x37.png'
FRAME_SIZE = (90, 37)
MARGIN = 0
SPACING = 0
FRAMES = [
    (0, 518, 90, 37),
    (90, 518, 90, 37),
    (180, 518, 90, 37),
    (270, 518, 90, 37),
]
TRIMMED = [
    (21, 527, 14, 22, 21, 9),
    (111, 527, 14, 22, 21, 9),
    (197, 527, 19, 21, 17, 9),
    (287, 527, 19, 21, 17, 9),
]
PIVOTS = [
    (7, 21),
    (7, 21),
    (9, 20),
    (9, 20),
]
